# Generated by Django 4.2.4 on 2023-09-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
